version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sandbox-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  sandbox-engine:
    build: .
    container_name: sandbox-engine-app
    ports:
      - "8085:8085"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_AUTOCONFIGURE_EXCLUDE=
      - APP_USE_QUEUE=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
