spring.application.name=sandbox-engine
# Exclude RabbitMQ autoconfiguration by default so local execution starts immediately without connection errors.
# To test with RabbitMQ broker, comment out the line below and make sure RabbitMQ is running.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
app.use-queue=false
server.port=8085
docker.host=npipe:////./pipe/dockerDesktopLinuxEngine
